# Proyecto Práctica 1 - Sesión 2

medirTiempos: medirTiempos.c algoritmos.o 
	gcc -g medirTiempos.c algoritmos.o -o medirTiempos 
algoritmos.o: algoritmos.c algoritmos.h
	gcc -c -g algoritmos.c
clean:
	rm *.o
