# Proyecto Práctica 3 - 

# Sesión 5 - Enunciado 1 Análisis experimetnal Algoritmos de Búsqueda

sesion5: medirTyContarV.c busqueda.o ordenacion.o
	gcc -g medirTyContarV.c busqueda.o ordenacion.o -o sesion5
busqueda.o: busqueda.c busqueda.h
	gcc -c -g busqueda.c
ordenacion.o: ordenacion.c ordenacion.h
	gcc -c -g ordenacion.c


# Varios
clean:
	rm *.o

